Задание 2. Добавлен README
gpb-it-factory/rysaev-telegram-bot pull request #2
Opened 2024-05-12 21:11 UTC by gazzsha

2024-05-14 09:40 UTC, konstantin-kozlovskiy commented
Добавь, пожалуйста, описание проекта, что собираешься делать, о чем этот репозиторий, просто UML диаграммы недостаточно )

2024-05-14 09:41 UTC, konstantin-kozlovskiy requested changes
Необходимо добавить больше информации, одной UML диаграммы недостаточно, напиши о чем проект?

2024-05-23 19:42 UTC, gazzsha commented
Задание 2. Добавлено описание проекта

2024-05-27 15:35 UTC, konstantin-kozlovskiy approved these changes

2024-05-30 18:31 UTC, merged